site_name: MineAcademy
site_url: https://kangarko.github.io/docs
repo_url: https://github.com/kangarko/docs
edit_uri: edit/main/docs/
repo_name: kangarko/docs

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - header.autohide
    - content.action.edit
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - navigation.expand
    - toc.follow
    - toc.integrate
    - navigation.top

plugins:
  - privacy
  - search
  - social
  - tags
  - git-revision-date-localized:
      enable_creation_date: false
  - git-committers:
      repository: kangarko/docs
      branch: main

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

copyright: >
  Copyright &copy; 2024 - MineAcademy –
  <a href="#__consent">Change cookie settings</a>