site_name: MineAcademy Docs
repo_name: MineAcademy Docs
site_url: https://docs.mineacademy.org
repo_url: https://github.com/kangarko/docs
extra_css:
  - assets/stylesheets/extra.css
theme:
  name: material
  logo: assets/branding/header-white.png
  favicon: assets/branding/logo-white.png
  font:
    code: JetBrains Mono
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Auto mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: octicons/sun-16
        name: Light mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: octicons/moon-24
        name: Dark mode

  features:
    - content.tabs.link
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.select
    - navigation.tabs
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.footer
    - content.action.view
    - content.action.edit
    - content.tooltips
    - toc.follow

nav:
  - Home: index.md
  - MineBot:
    - minebot/index.md
    - Get Started: 
      - minebot/get_started/index.md
    - Installation: 
      - minebot/installation/index.md
    - Configuration:
      - minebot/configuration/index.md
    - Localization:
      - minebot/localization/index.md
  - Bans-Plugin:
      - bans/index.md
      - Commands:
          - bans/commands/index.md
      - Compatibility:
          - bans/compatability/index.md
      - Discord:
          - bans/discord/index.md
      - Installation:
          - bans/installation/index.md
      - Proxy:
          - bans/proxy/index.md


plugins:
  - autorefs
  - search
  - privacy
  - open-in-new-tab
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
      skip_classes:
         - no-lightbox

extra:
  CNAME: docs.mineacademy.org
  social:
    - icon: fontawesome/solid/globe
      link: https://mineacademy.org
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/aMSnAcx
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@kangarko

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
copyright: >
  &copy; MineAcademy | Made by Jannick and Egehan
